name: Tag and release
on: push
jobs:
    release:
        if: github.ref == 'refs/heads/master'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository code
              uses: actions/checkout@v2
            - name: Create tag
              uses: mathieudutour/github-tag-action@v6.1
              id: tag_version_dry_run
              with:
                  dry_run: true
                  github_token: ${{ secrets.GITHUB_TOKEN }}
            - name: Append commit hash as build metadata and push tag
              uses: mathieudutour/github-tag-action@v6.1
              with:
                  custom_tag: "${{ steps.tag_version_dry_run.outputs.new_version }}+${{ github.sha }}"
                  github_token: ${{ secrets.GITHUB_TOKEN }}
