name: Tag and release
on: push
jobs:
    release:
        if: github.ref == 'refs/heads/master'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository code
              uses: actions/checkout@v2
            - name: Bump version and push tag
              uses: mathieudutour/github-tag-action@v6.1
              with:
                  tag: ${{ github.sha }}
                  github_token: ${{ secrets.GITHUB_TOKEN }}
