name: Validate pull requests
on:
    pull_request:

concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

env:
    ROLE_TO_ASSUME: arn:aws:iam::692314432491:role/github-terraform-repo-role
    AWS_REGION: eu-west-2 # match the region specified in accounts/aws-dev/global/cross-region
    ROOT_TERRAGRUNT_DIRECTORY: accounts/aws-dev
    PLAN_OUTPUT_NAME: terragrunt-plan-aws-dev-output
    PLAN_COMBINED_OUTPUT_FILE: plan-output.txt
    TERRAGRUNT_VERSION: 0.44.5
    TERRAFORM_VERSION: 1.3.9

permissions:
    # This is needed for aws-actions/configure-aws-credentials to work
    id-token: write
    contents: read
    # This is needed for terraform action to write comments on a PR
    pull-requests: write

jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository code
              uses: actions/checkout@v2
              with:
                  terraform_version: ${{ env.TERRAFORM_VERSION }}
            - name: Terraform Format Check
              id: format
              run: terraform fmt -check -recursive -no-color
              continue-on-error: true
